### ISSUE TITLE
IE8 Invalid argument (index out of bounds)

### ISSUE THREAD

**Issue by zyllorion** [tildeio/htmlbars#259]
```
      run: function(target, method /*, args */) {
        var onError = getOnError(this.options);

        this.begin();

        if (!method) {
          method = target;
          target = null;
        }

        if (isString(method)) {
          method = target[method];
        }

        var args = slice.call(arguments, 2);

        // guard against Safari 6's double-finally bug
        var didFinally = false;

        if (onError) {
          try {
            return method.apply(target, args);
          } catch(error) {
            onError(error);
          } finally {
            if (!didFinally) {
              didFinally = true;
              this.end();
            }
          }
        } else {
          try {
            return method.apply(target, args);
          } finally {
            if (!didFinally) {
              didFinally = true;
>>>>>>>>>              this.end();
            }
          }
        }
      },
```
The line highlighted above seems to cause the exception:
```
Invalid argument. {
	[prototype] : {...},
	description : "Invalid argument.",
	message : "Invalid argument.",
	number : -2147024809
}
```
I think it most likely occurs when the following executes:
```
 prototype.childAtIndex = function(element, index) {
      return element.childNodes.item(index);
    };
```
element looks like this: [object DispHTMLDocument]
and contains 0 childNodes

If I change the code to this:
```
    prototype.childAtIndex = function(element, index) {
      if(element.childNodes.length>index)
        return element.childNodes.item(index);
      else
        return null;
    };
```
I get
SCRIPT5022: a fragment parent must have boundary nodes in order to detect insertion

I'm not sure that element has been passed correctly as some of the properties have strange values, e.g. location: Unexpected call to method or property. mimetype/domain/fileSize: nspecified error. div: 'div' is undefined.

This is reproducible in IE11 using ie8 compatibility mode:
Ember      : 1.11.0-beta.1+canary.59757239
Ember Data : 1.0.0-beta.14.1
ember-cli: 0.1.7

**Comment by oneeman** [comment]
Thanks for pinpointing it!  At first glance, it looks like the same problem addressed by @salzhrani at https://github.com/tildeio/htmlbars/pull/247/files#diff-ae9f94d48470b7d9baaf54b27751f728R145, in which case we should be good on this once that PR gets merged (we can leave this issue open until it's confirmed as fixed after that happens).

**Comment by oneeman** [comment]
(Well, except the stuff you mention at the end, we'll have to look at that, too)

**Comment by mixonic** [comment]
@zyllorion can you take a look at master and see what is still an issue? We've fixed quite a few items.

**Comment by zyllorion** [comment]
Looks great! :-) Thanks for the fixes.
